- name: Start Kong
  shell: /usr/bin/node /usr/local/bin/kong start
  when: kong_action | default('') == "kong_start"

- name: Stop Kong
  shell: /usr/bin/node /usr/local/bin/kong stop
  when: kong_action | default('') == "kong_stop"

- name: Restart Kong
  shell: /usr/bin/node /usr/local/bin/kong restart
  when: kong_action | default('') == "kong_restart"
